# This pipeline will just build PulseAudio to be sure we dont break

  trigger:
    - working
    
  pool:
    vmImage: 'ubuntu-20.04'

  variables:
    prefix: '/usr/local'
    
  steps:
    - checkout: self
  
    - script: sudo apt-get update && sudo apt-get install --no-install-recommends -y
              build-essential
              autopoint
              autoconf
              libltdl-dev
              libtool
              libxtst-dev
              libx11-dev
              libx11-xcb-dev
              libsndfile1
              libcap-dev
              libsndfile-dev
              ninja-build
              pkg-config
              gettext
              software-properties-common
      displayName: 'Install Dependencies'

    - script: sudo pip3 install meson
      displayName: 'Install Meson (from PIP)'

    - script: meson --prefix=$(prefix) build
                    -Ddatabase=simple
                    -Ddoxygen=false
                    -Dgsettings=disabled
                    -Dman=false
                    -Dtests=false
      displayName: 'Meson (pulseaudio)'

    - script: ninja -C build -j8
      displayName: 'Ninja (pulseaudio)'
